// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfm930FYF3uIpBzLQ6MUv6Y0HqR5CbQgM',
    appId: '1:625420286680:web:f3ceb22d57b4614fe875ad',
    messagingSenderId: '625420286680',
    projectId: 'task-manger-app-72c21',
    authDomain: 'task-manger-app-72c21.firebaseapp.com',
    storageBucket: 'task-manger-app-72c21.firebasestorage.app',
    measurementId: 'G-F1CVTLFFEY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDU0e8hPzHyY7KdaYZGzp1vlKS1TDrIvb8',
    appId: '1:625420286680:android:dcf79265fa39266fe875ad',
    messagingSenderId: '625420286680',
    projectId: 'task-manger-app-72c21',
    storageBucket: 'task-manger-app-72c21.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAO_hO2gSIP32IiiGaq91OYKtPSJhyEk1I',
    appId: '1:625420286680:ios:cb28485e64646497e875ad',
    messagingSenderId: '625420286680',
    projectId: 'task-manger-app-72c21',
    storageBucket: 'task-manger-app-72c21.firebasestorage.app',
    iosBundleId: 'com.example.taskMangerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAO_hO2gSIP32IiiGaq91OYKtPSJhyEk1I',
    appId: '1:625420286680:ios:cb28485e64646497e875ad',
    messagingSenderId: '625420286680',
    projectId: 'task-manger-app-72c21',
    storageBucket: 'task-manger-app-72c21.firebasestorage.app',
    iosBundleId: 'com.example.taskMangerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfm930FYF3uIpBzLQ6MUv6Y0HqR5CbQgM',
    appId: '1:625420286680:web:154c78dee88d3328e875ad',
    messagingSenderId: '625420286680',
    projectId: 'task-manger-app-72c21',
    authDomain: 'task-manger-app-72c21.firebaseapp.com',
    storageBucket: 'task-manger-app-72c21.firebasestorage.app',
    measurementId: 'G-N7KLF04Q7J',
  );
}
